### ISSUE TITLE
InterruptedError: Failed to generate output of length 1 after 3 retries.

### ISSUE THREAD

**Issue by wjcheon** [Marker-Inc-Korea/AutoRAG#603]
Dear all 

When i make a qa.parquet. 
I set to "--qa_size" as 5. This condition is properly working. 
But, I changed the size as 10. 
I faced the error:

InterruptedError: Failed to generate output of length 1 after 3 retries.

Please give me your hands. 

Thks. 

Wonjoong Cheon

**Comment by vkehfdl1** [comment]
@wjcheon Hello!

I think you used too large number of qa_size.
The `qa_size` that you mentioned means, "I want to generate {qa_size} questions in the **one** chunk"
So, it is possible that 10 questions can't be generated in only **one chunk**. Even human generated it.  

Thus, you have to lower the size of it.

**Comment by wjcheon** [comment]
Oh, hello Donggyu-Kim,

'qa_df = make_single_content_qa(corpus_df, content_size=50, qa_creation_func=generate_qa_llama_index_by_ratio,
llm=llm, prompts_ratio=ratio_dict, question_num_per_content=1, batch=6)'

Then this example wouldn't be appropriate for the homepage, right?

I'm curious about another one. My corpus data has 308 rows. 
If I set qa_size to 3, it seems like 308*3 QnA data should be created, but only 3 are generated.

 Why is this happening? I'm also using the make_single_content_qa function.

**Comment by wjcheon** [comment]
@vkehfdl1  

I tested using the example of newjeans. 
I think the "qa_size" mean the number of question what i want to generate. 
Isnt it?

**Comment by vkehfdl1** [comment]
@wjcheon 

You mean this file at our AutoRAG tutorial, right?
https://github.com/Marker-Inc-Korea/AutoRAG-tutorial-ko/blob/main/make_qa.py

You are right. In that file, the `qa_size` is the number of question. 
Please let me know which file or which code you are using. Because I can't get it right when you don't specify what code you are using.

A. You need to make issue at tutorial-ko repo, since this is not the `AutoRAG` bug. 
B. I think the LLM couldn't generate the question somehow. 
The first thing you can do is check the corpus chunks. It can be contain empty chunk or too small chunk. If the chunk too small, it is hard to generate question.
The second thing you can try is to increase retries. You can use parameter `max_retries` (int type)

The error occurs when the LLM couldn't generate question properly even three retries.
Since this is not the error at the codebase, I am closing this issue.

Thanks.
