### ISSUE TITLE
[Feature Request] Delete nest_asyncio dependency at library (FastAPI server execution)

### ISSUE THREAD

**Issue by vkehfdl1** [Marker-Inc-Korea/AutoRAG#640]
**Is your feature request related to a problem? Please describe.**
Using `nest_asyncio` actually breaks the design of the `asyncio`. But we had to use it because of the FastAPI server.
In this issue, we have to figure out how to use FastAPI server and AutoRAG without using `nest_asyncio` since it is not intended usage of `asyncio` [Relevant Link](https://stackoverflow.com/questions/59740704/correct-use-constraints-of-use-of-nest-asyncio)

**Describe the solution you'd like**

**Describe alternatives you've considered**
We can just use it. Actually this issue is not that serious yet.

**Additional context**

**Comment by rjwharry** [comment]
@vkehfdl1  How about using Flask instead of FastAPI?  
We have to use ASGI(uvicorn) to run FastAPI, but cannot avoid running event loop.  
So my suggestion is using Flask instead. As you know, Flask is WSGI Application and it will not cause conflict of event loop.  
I tested on my local, and it works properly. I can make draft PR for you

**Comment by vkehfdl1** [comment]
@rjwharry 
Great idea! It will be great you can make PR for it.
I will assign to you in this issue. 
Thank you very much
