### ISSUE TITLE
Add reranker test to ignore settings

### ISSUE THREAD

**Issue by bwook00** [Marker-Inc-Korea/AutoRAG#79]

**Comment by vkehfdl1** [comment]
All reranker needs to run as local model, and it is too hard to run at github actions.
It takes lots of time to download it, and it surpass storage of github action runner.

So, we have to ignore reranker tests at GitHub actions, just test it locally.

Because `modal` looks impossible to run `pytest`. 

Reason why : it deploy seperate image on cloud, and it install `AutoRAG` as well. It is totally different environment. So, it can’t import local import statements or modified Reranker test before deployment. It is useless when it can’t test local changes.
