### ISSUE TITLE
[Question] override default prompt with custom?

### ISSUE THREAD

**Issue by kun432** [Marker-Inc-Korea/AutoRAG#851]
In Data Creation process, is it possible to override default prompts for generating queries (and ground truth answers) with my own customs?

This is just my personal opnion, but generated queries makes me feel a little too descriptive (sometimes 2 topics in 1 question) and unnatural as humans' query (of course it's not by human, but human queries are generally much more short). It would be nice to have options to override.

Thanks!

**Comment by vkehfdl1** [comment]
@kun432 
Hello! 

First thing, I will tell you how to use your custom prompt.
In the each data creation function, the inputs are basically a "function". So all you need to do is to make a function for LLM prompting.

Fox example, you can make a custom function like this. The only essential parameter is row, which is dictionary that contains a one column of the target dataframe. Plus be sure make this as async function.

```python
async def gen_query_custom(row: dict, llm: BaseLLM,) -> dict:
	# The input row looks like this:
	# {
	# 	"qid": "43332-455",
	# 	"retrieval_gt": [["doc_id_1"]],
	# 	"retrieval_gt_contents": [["Sample Passage Content"]],
	# }
	
	context = list(itertools.chain.from_iterable(row["retrieval_gt_contents"]))
	context_str = "Text:\n" + "\n".join(
		[f"{i + 1}. {c}" for i, c in enumerate(context)]
	)
	prompt = f"""Please generate question based on the query. Really natural! BE NATURAL!
	Given Context:
	{context_str}
	
	Generated Question:
	"""
	chat_response: ChatResponse = await llm.achat(messages=[
		ChatMessage(role=MessageRole.USER, content=prompt),
	])
	row["query"] = chat_response.message.content
	return row
```

You can use this function like below.
```python
llm = OpenAI(model="gpt-4o")
qa = QA(qa_df)
qa.make_retrieval_gt_contents().batch_apply(gen_query_custom, llm=llm)
```

---

Second, It can be unnatural because human is not too specific at some question.
Why don't you use `compress_ragas` evolving method. It can be good for simplify the too descriptive questions.

**Comment by kun432** [comment]
@vkehfdl1 

Thanks! just starting out AutoRAG so I hadn't caught up on evolving method. That's good to know!
Will try both.
