### ISSUE TITLE
llm token management + strategy

### ISSUE THREAD

**Issue by bwook00** [Marker-Inc-Korea/AutoRAG#92]
Need to manage input token on node using LLM. Will be supported in the next version.

**Comment by vkehfdl1** [comment]
[What to do?]

At first, this is a 'token strategy'. It means, you can set token limitation when optimizing each process. Some process consume many token to llm, and it effects overall pricing and speed.
Plus, it matters because the devs sometimes wants to monitor their token usage. 

[Suggestion]

I think it can be like python "logger" for llm token management. 

1. The python logger using 'singleton instance' at each logger name. 
We can define token logger instance like that.
2. When init each token logger, you can set tokenizer for counting it. The supported tokenizer might be `tiktoken` and `AutoTokenier` from now.
3. When log to instance, it logs automatically. It can save to separate log file, or csv.
Also, it supports sum or average of token usage. 
4. It can be cool we can reset or pause the token save. Like the record feature.

With this, we can easily collect token data at optimization process, without modifying any function input. 

I think it can be a standalone library for everyone wants to logging their token.


+ There are repo like `LLMTelemetry` that supports monitoring LLM calls. It can be a solution? Try to look at it.
